CREATE USER IF NOT EXISTS 'keycloak'@'%' IDENTIFIED BY 'keycloak';
CREATE DATABASE IF NOT EXISTS keycloak CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, ALTER ROUTINE, EXECUTE ON keycloak.* TO 'keycloak'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'userservice'@'%' IDENTIFIED BY 'userservice';
CREATE DATABASE IF NOT EXISTS userservice CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT SELECT, INSERT, UPDATE, DELETE ON userservice.* TO 'userservice'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'agencyservice'@'%' IDENTIFIED BY 'agencyservice';
CREATE DATABASE IF NOT EXISTS agencyservice CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT SELECT ON agencyservice.* TO 'agencyservice'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'liquibase'@'%' IDENTIFIED BY 'liquibase';
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, ALTER ROUTINE, EXECUTE ON userservice.* TO 'liquibase'@'%';
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, ALTER ROUTINE, EXECUTE ON agencyservice.* TO 'liquibase'@'%';
FLUSH PRIVILEGES;